version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9500:80"  # Sirve frontend en http://localhost:9500
    depends_on:
      - proxy

  proxy:
    build:
      context: ./node-server
      dockerfile: Dockerfile-node
    ports:
      - "3000:3000"  # Proxy escucha en http://localhost:3000
